//! Hand-rolled minimal Protobuf encoder for TRON `Transaction.raw`.
//!
//! TRON's wire format is google Protobuf (proto3). We encode just enough of
//! the schema to ship a native TRX `TransferContract`. Keeping this in-tree
//! avoids pulling `prost` + `protoc` for one message family.
//!
//! Field map (verified against `protocol/Tron.proto` upstream):
//!
//! ```text
//! Transaction.raw {
//!     bytes ref_block_bytes = 1;
//!     bytes ref_block_hash  = 4;
//!     int64 expiration      = 8;
//!     repeated Contract contract = 11;
//!     int64 timestamp       = 14;
//!     int64 fee_limit       = 18;
//! }
//! Contract { ContractType type = 1; google.protobuf.Any parameter = 2; }
//! google.protobuf.Any { string type_url = 1; bytes value = 2; }
//! TransferContract {
//!     bytes owner_address = 1;  // 21 bytes (0x41 ‖ hash160)
//!     bytes to_address    = 2;
//!     int64 amount        = 3;  // sun
//! }
//! ```
//!
//! Reference vector pinned in tests is generated by `scripts/tron-ref-vector.mjs`
//! using `tronweb`'s native protobuf encoder, so we get byte-equality with the
//! validator-side decoder rather than guessing at field order or wire types.

const TRANSFER_TYPE_URL: &str = "type.googleapis.com/protocol.TransferContract";
const TRIGGER_TYPE_URL: &str = "type.googleapis.com/protocol.TriggerSmartContract";

/// `Contract.ContractType` enum value for the native TRX `TransferContract`.
pub const CONTRACT_TYPE_TRANSFER: u64 = 1;
/// `Contract.ContractType` enum value for `TriggerSmartContract` (TRC-20 etc.).
pub const CONTRACT_TYPE_TRIGGER_SMART_CONTRACT: u64 = 31;

// ── Wire-format primitives ──────────────────────────────────────────────────

fn write_varint(out: &mut Vec<u8>, mut v: u64) {
    while v >= 0x80 {
        out.push((v as u8) | 0x80);
        v >>= 7;
    }
    out.push(v as u8);
}

fn write_tag(out: &mut Vec<u8>, field_num: u32, wire_type: u32) {
    write_varint(out, ((field_num as u64) << 3) | (wire_type as u64));
}

fn write_bytes_field(out: &mut Vec<u8>, field_num: u32, data: &[u8]) {
    write_tag(out, field_num, 2);
    write_varint(out, data.len() as u64);
    out.extend_from_slice(data);
}

fn write_int64_field(out: &mut Vec<u8>, field_num: u32, v: i64) {
    write_tag(out, field_num, 0);
    // proto3 int64 is plain varint over the two's-complement representation.
    // Negative values would balloon to 10 bytes; for our positive timestamps
    // and amounts this is fine.
    write_varint(out, v as u64);
}

// ── TransferContract / Any / Contract / raw ─────────────────────────────────

pub fn encode_transfer_contract(owner: &[u8], to: &[u8], amount: i64) -> Vec<u8> {
    let mut out = Vec::with_capacity(2 + owner.len() + 2 + to.len() + 2 + 10);
    write_bytes_field(&mut out, 1, owner);
    write_bytes_field(&mut out, 2, to);
    write_int64_field(&mut out, 3, amount);
    out
}

pub fn encode_any_transfer(transfer: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(2 + TRANSFER_TYPE_URL.len() + 2 + transfer.len());
    write_bytes_field(&mut out, 1, TRANSFER_TYPE_URL.as_bytes());
    write_bytes_field(&mut out, 2, transfer);
    out
}

pub fn encode_contract_transfer(any: &[u8]) -> Vec<u8> {
    encode_contract_envelope(CONTRACT_TYPE_TRANSFER, any)
}

/// Wrap an Any-encoded payload in `Contract { type, parameter }` for an
/// arbitrary `ContractType` enum value. Use [`CONTRACT_TYPE_TRANSFER`] for
/// native TRX transfers and [`CONTRACT_TYPE_TRIGGER_SMART_CONTRACT`] for
/// TRC-20 / TVM smart contract calls.
pub fn encode_contract_envelope(contract_type: u64, any: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(4 + any.len());
    write_tag(&mut out, 1, 0);
    write_varint(&mut out, contract_type);
    write_bytes_field(&mut out, 2, any);
    out
}

/// `TriggerSmartContract` proto:
///   bytes owner_address    = 1 (caller's 21-byte T-address)
///   bytes contract_address = 2 (TRC-20 contract's 21-byte T-address)
///   int64 call_value       = 3 (TRX attached to the call — 0 for TRC-20 transfer)
///   bytes data             = 4 (ABI calldata)
///
/// `call_value`/`call_token_value`/`token_id` are omitted when 0 — proto3 default.
pub fn encode_trigger_smart_contract(
    owner: &[u8],
    contract: &[u8],
    call_value: i64,
    data: &[u8],
) -> Vec<u8> {
    let mut out = Vec::with_capacity(8 + owner.len() + contract.len() + data.len());
    write_bytes_field(&mut out, 1, owner);
    write_bytes_field(&mut out, 2, contract);
    if call_value != 0 {
        write_int64_field(&mut out, 3, call_value);
    }
    write_bytes_field(&mut out, 4, data);
    out
}

/// Wrap a `TriggerSmartContract` body in `google.protobuf.Any`.
pub fn encode_any_trigger(trigger: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(2 + TRIGGER_TYPE_URL.len() + 2 + trigger.len());
    write_bytes_field(&mut out, 1, TRIGGER_TYPE_URL.as_bytes());
    write_bytes_field(&mut out, 2, trigger);
    out
}

/// Encode `Transaction.raw`. `fee_limit_sun` is omitted when None — TRON only
/// requires it for `TriggerSmartContract`, never for native `TransferContract`.
/// Including it produces a non-canonical body that fails the validator's
/// raw_data_hex ↔ raw_data JSON cross-check.
#[allow(clippy::too_many_arguments)]
pub fn encode_raw_data(
    ref_block_bytes: &[u8; 2],
    ref_block_hash: &[u8; 8],
    expiration_ms: i64,
    contract_bytes: &[u8],
    timestamp_ms: i64,
    fee_limit_sun: Option<i64>,
) -> Vec<u8> {
    let mut out = Vec::with_capacity(48 + contract_bytes.len());
    write_bytes_field(&mut out, 1, ref_block_bytes);
    write_bytes_field(&mut out, 4, ref_block_hash);
    write_int64_field(&mut out, 8, expiration_ms);
    write_bytes_field(&mut out, 11, contract_bytes);
    write_int64_field(&mut out, 14, timestamp_ms);
    if let Some(fl) = fee_limit_sun {
        write_int64_field(&mut out, 18, fl);
    }
    out
}

/// One-shot helper: build the full `Transaction.raw` bytes for a TRC-20
/// `transfer(address,uint256)` call. `fee_limit_sun` is mandatory (validators
/// require it for TVM calls — unlike native TransferContract per L-017) and
/// must be > 0; recommend ~100 TRX (`100_000_000` sun) — refunded if unused.
#[allow(clippy::too_many_arguments)]
pub fn build_trc20_transfer_raw_data(
    owner_21: &[u8],
    contract_21: &[u8],
    calldata: &[u8],
    ref_block_bytes: &[u8; 2],
    ref_block_hash: &[u8; 8],
    expiration_ms: i64,
    timestamp_ms: i64,
    fee_limit_sun: i64,
) -> Vec<u8> {
    let trigger = encode_trigger_smart_contract(owner_21, contract_21, 0, calldata);
    let any = encode_any_trigger(&trigger);
    let contract = encode_contract_envelope(CONTRACT_TYPE_TRIGGER_SMART_CONTRACT, &any);
    encode_raw_data(
        ref_block_bytes,
        ref_block_hash,
        expiration_ms,
        &contract,
        timestamp_ms,
        Some(fee_limit_sun),
    )
}

/// One-shot helper: build the full `Transaction.raw` bytes for a TransferContract.
#[allow(clippy::too_many_arguments)]
pub fn build_transfer_raw_data(
    owner_21: &[u8],
    to_21: &[u8],
    amount_sun: i64,
    ref_block_bytes: &[u8; 2],
    ref_block_hash: &[u8; 8],
    expiration_ms: i64,
    timestamp_ms: i64,
    fee_limit_sun: Option<i64>,
) -> Vec<u8> {
    let transfer = encode_transfer_contract(owner_21, to_21, amount_sun);
    let any = encode_any_transfer(&transfer);
    let contract = encode_contract_transfer(&any);
    encode_raw_data(
        ref_block_bytes,
        ref_block_hash,
        expiration_ms,
        &contract,
        timestamp_ms,
        fee_limit_sun,
    )
}

/// Build the JSON shape `tronweb` POSTs as `raw_data` in
/// `/wallet/broadcasttransaction`. The validator decodes this object
/// independently and cross-checks it against `raw_data_hex`.
///
/// Keep this function in lock-step with [`build_transfer_raw_data`] — the JSON
/// shape and the bytes MUST describe the same logical transaction.
#[allow(clippy::too_many_arguments)]
pub fn build_transfer_raw_data_json(
    owner_21: &[u8],
    to_21: &[u8],
    amount_sun: i64,
    ref_block_bytes: &[u8; 2],
    ref_block_hash: &[u8; 8],
    expiration_ms: i64,
    timestamp_ms: i64,
) -> serde_json::Value {
    serde_json::json!({
        "contract": [{
            "parameter": {
                "value": {
                    "owner_address": hex::encode(owner_21),
                    "to_address": hex::encode(to_21),
                    "amount": amount_sun,
                },
                "type_url": TRANSFER_TYPE_URL,
            },
            "type": "TransferContract",
        }],
        "ref_block_bytes": hex::encode(ref_block_bytes),
        "ref_block_hash": hex::encode(ref_block_hash),
        "expiration": expiration_ms,
        "timestamp": timestamp_ms,
    })
}

// ── Bytes → JSON (for broadcast `raw_data` object) ──────────────────────────

fn read_varint(buf: &[u8]) -> Option<(u64, usize)> {
    let mut v = 0u64;
    let mut shift = 0u32;
    for (i, &b) in buf.iter().enumerate() {
        v |= ((b & 0x7f) as u64) << shift;
        if b & 0x80 == 0 {
            return Some((v, i + 1));
        }
        shift += 7;
        if shift >= 64 {
            return None;
        }
    }
    None
}

fn parse_tag(buf: &[u8]) -> Option<(u32, u32, usize)> {
    let (raw, n) = read_varint(buf)?;
    Some(((raw >> 3) as u32, (raw & 0x7) as u32, n))
}

fn read_len_delimited(buf: &[u8]) -> Option<(&[u8], usize)> {
    let (len, n) = read_varint(buf)?;
    let total = n + len as usize;
    if total > buf.len() {
        return None;
    }
    Some((&buf[n..total], total))
}

/// Decode a `TransferContract` `Transaction.raw` blob back into the JSON shape
/// `tronweb` POSTs as the `raw_data` field of `/wallet/broadcasttransaction`.
/// The validator independently parses our `raw_data_hex` and cross-checks it
/// against this JSON object — they MUST describe the same logical tx.
pub fn decode_transfer_raw_to_json(mut buf: &[u8]) -> Result<serde_json::Value, &'static str> {
    let mut ref_block_bytes: Option<String> = None;
    let mut ref_block_hash: Option<String> = None;
    let mut expiration: Option<i64> = None;
    let mut timestamp: Option<i64> = None;
    let mut fee_limit: Option<i64> = None;
    let mut contract_value: Option<serde_json::Value> = None;

    while !buf.is_empty() {
        let (field, wire, n) = parse_tag(buf).ok_or("tag")?;
        buf = &buf[n..];
        match (field, wire) {
            (1, 2) => {
                let (b, n) = read_len_delimited(buf).ok_or("ref_block_bytes")?;
                ref_block_bytes = Some(hex::encode(b));
                buf = &buf[n..];
            }
            (4, 2) => {
                let (b, n) = read_len_delimited(buf).ok_or("ref_block_hash")?;
                ref_block_hash = Some(hex::encode(b));
                buf = &buf[n..];
            }
            (8, 0) => {
                let (v, n) = read_varint(buf).ok_or("expiration")?;
                expiration = Some(v as i64);
                buf = &buf[n..];
            }
            (11, 2) => {
                let (contract_buf, n) = read_len_delimited(buf).ok_or("contract")?;
                contract_value = Some(decode_contract_to_json(contract_buf)?);
                buf = &buf[n..];
            }
            (14, 0) => {
                let (v, n) = read_varint(buf).ok_or("timestamp")?;
                timestamp = Some(v as i64);
                buf = &buf[n..];
            }
            (18, 0) => {
                let (v, n) = read_varint(buf).ok_or("fee_limit")?;
                fee_limit = Some(v as i64);
                buf = &buf[n..];
            }
            // Skip unknown fields by advancing past their payload.
            (_, 0) => {
                let (_, n) = read_varint(buf).ok_or("varint skip")?;
                buf = &buf[n..];
            }
            (_, 2) => {
                let (_, n) = read_len_delimited(buf).ok_or("len skip")?;
                buf = &buf[n..];
            }
            _ => return Err("unsupported wire type"),
        }
    }

    let mut obj = serde_json::Map::new();
    obj.insert(
        "contract".into(),
        serde_json::Value::Array(vec![contract_value.ok_or("missing contract")?]),
    );
    obj.insert(
        "ref_block_bytes".into(),
        serde_json::Value::String(ref_block_bytes.ok_or("missing ref_block_bytes")?),
    );
    obj.insert(
        "ref_block_hash".into(),
        serde_json::Value::String(ref_block_hash.ok_or("missing ref_block_hash")?),
    );
    obj.insert(
        "expiration".into(),
        serde_json::Value::Number(expiration.ok_or("missing expiration")?.into()),
    );
    if let Some(fl) = fee_limit {
        obj.insert("fee_limit".into(), serde_json::Value::Number(fl.into()));
    }
    obj.insert(
        "timestamp".into(),
        serde_json::Value::Number(timestamp.ok_or("missing timestamp")?.into()),
    );
    Ok(serde_json::Value::Object(obj))
}

fn decode_contract_to_json(mut buf: &[u8]) -> Result<serde_json::Value, &'static str> {
    let mut type_num: Option<u64> = None;
    let mut parameter_buf: Option<Vec<u8>> = None;
    while !buf.is_empty() {
        let (field, wire, n) = parse_tag(buf).ok_or("contract tag")?;
        buf = &buf[n..];
        match (field, wire) {
            (1, 0) => {
                let (v, n) = read_varint(buf).ok_or("contract type")?;
                type_num = Some(v);
                buf = &buf[n..];
            }
            (2, 2) => {
                let (any_buf, n) = read_len_delimited(buf).ok_or("contract parameter")?;
                parameter_buf = Some(any_buf.to_vec());
                buf = &buf[n..];
            }
            _ => return Err("unexpected contract field"),
        }
    }
    let type_num = type_num.ok_or("contract type missing")?;
    let parameter_buf = parameter_buf.ok_or("contract parameter missing")?;
    let (type_str, parameter) = match type_num {
        CONTRACT_TYPE_TRANSFER => (
            "TransferContract",
            decode_any_to_json(&parameter_buf, decode_transfer_value_to_json)?,
        ),
        CONTRACT_TYPE_TRIGGER_SMART_CONTRACT => (
            "TriggerSmartContract",
            decode_any_to_json(&parameter_buf, decode_trigger_value_to_json)?,
        ),
        other => {
            return Err(Box::leak(
                format!("unsupported contract type {other}").into_boxed_str(),
            ))
        }
    };
    Ok(serde_json::json!({
        "parameter": parameter,
        "type": type_str,
    }))
}

fn decode_any_to_json<F>(mut buf: &[u8], decode_value: F) -> Result<serde_json::Value, &'static str>
where
    F: Fn(&[u8]) -> Result<serde_json::Value, &'static str>,
{
    let mut type_url: Option<String> = None;
    let mut value_bytes: Option<Vec<u8>> = None;
    while !buf.is_empty() {
        let (field, wire, n) = parse_tag(buf).ok_or("any tag")?;
        buf = &buf[n..];
        match (field, wire) {
            (1, 2) => {
                let (b, n) = read_len_delimited(buf).ok_or("any type_url")?;
                type_url = Some(String::from_utf8(b.to_vec()).map_err(|_| "type_url utf8")?);
                buf = &buf[n..];
            }
            (2, 2) => {
                let (b, n) = read_len_delimited(buf).ok_or("any value")?;
                value_bytes = Some(b.to_vec());
                buf = &buf[n..];
            }
            _ => return Err("unexpected any field"),
        }
    }
    let value = decode_value(&value_bytes.ok_or("any value missing")?)?;
    Ok(serde_json::json!({
        "value": value,
        "type_url": type_url.ok_or("any type_url missing")?,
    }))
}

fn decode_trigger_value_to_json(mut buf: &[u8]) -> Result<serde_json::Value, &'static str> {
    let mut owner: Option<String> = None;
    let mut contract: Option<String> = None;
    let mut call_value: i64 = 0;
    let mut data: Option<String> = None;
    while !buf.is_empty() {
        let (field, wire, n) = parse_tag(buf).ok_or("trigger tag")?;
        buf = &buf[n..];
        match (field, wire) {
            (1, 2) => {
                let (b, n) = read_len_delimited(buf).ok_or("trigger owner")?;
                owner = Some(hex::encode(b));
                buf = &buf[n..];
            }
            (2, 2) => {
                let (b, n) = read_len_delimited(buf).ok_or("trigger contract")?;
                contract = Some(hex::encode(b));
                buf = &buf[n..];
            }
            (3, 0) => {
                let (v, n) = read_varint(buf).ok_or("call_value")?;
                call_value = v as i64;
                buf = &buf[n..];
            }
            (4, 2) => {
                let (b, n) = read_len_delimited(buf).ok_or("trigger data")?;
                data = Some(hex::encode(b));
                buf = &buf[n..];
            }
            // Skip optional call_token_value (5) / token_id (6) / etc.
            (_, 0) => {
                let (_, n) = read_varint(buf).ok_or("varint skip")?;
                buf = &buf[n..];
            }
            (_, 2) => {
                let (_, n) = read_len_delimited(buf).ok_or("len skip")?;
                buf = &buf[n..];
            }
            _ => return Err("unexpected trigger field"),
        }
    }
    let mut obj = serde_json::Map::new();
    obj.insert(
        "owner_address".into(),
        serde_json::Value::String(owner.ok_or("trigger owner missing")?),
    );
    obj.insert(
        "contract_address".into(),
        serde_json::Value::String(contract.ok_or("trigger contract missing")?),
    );
    if call_value != 0 {
        obj.insert(
            "call_value".into(),
            serde_json::Value::Number(call_value.into()),
        );
    }
    obj.insert(
        "data".into(),
        serde_json::Value::String(data.ok_or("trigger data missing")?),
    );
    Ok(serde_json::Value::Object(obj))
}

fn decode_transfer_value_to_json(mut buf: &[u8]) -> Result<serde_json::Value, &'static str> {
    let mut owner: Option<String> = None;
    let mut to: Option<String> = None;
    let mut amount: Option<i64> = None;
    while !buf.is_empty() {
        let (field, wire, n) = parse_tag(buf).ok_or("value tag")?;
        buf = &buf[n..];
        match (field, wire) {
            (1, 2) => {
                let (b, n) = read_len_delimited(buf).ok_or("owner")?;
                owner = Some(hex::encode(b));
                buf = &buf[n..];
            }
            (2, 2) => {
                let (b, n) = read_len_delimited(buf).ok_or("to")?;
                to = Some(hex::encode(b));
                buf = &buf[n..];
            }
            (3, 0) => {
                let (v, n) = read_varint(buf).ok_or("amount")?;
                amount = Some(v as i64);
                buf = &buf[n..];
            }
            _ => return Err("unexpected transfer field"),
        }
    }
    Ok(serde_json::json!({
        "owner_address": owner.ok_or("owner missing")?,
        "to_address": to.ok_or("to missing")?,
        "amount": amount.ok_or("amount missing")?,
    }))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn varint_roundtrip() {
        let cases = [0u64, 1, 127, 128, 255, 16_383, 16_384, 1_000_000, u64::MAX];
        for c in cases {
            let mut buf = Vec::new();
            write_varint(&mut buf, c);
            let (v, n) = read_varint(&buf).unwrap();
            assert_eq!(v, c, "value mismatch");
            assert_eq!(n, buf.len(), "consumed length mismatch");
        }
    }

    /// Reference vector captured via `node scripts/tron-ref-vector.mjs`.
    /// Asserts byte-for-byte parity against `tronweb`'s native protobuf encoder.
    #[test]
    fn proto_matches_tronweb_reference() {
        let owner = hex::decode("411111111111111111111111111111111111111111").unwrap();
        let to = hex::decode("412222222222222222222222222222222222222222").unwrap();
        let amount: i64 = 1_000_000;
        let ref_block_bytes: [u8; 2] = [0x00, 0x01];
        let ref_block_hash: [u8; 8] = [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08];
        let timestamp: i64 = 1_700_000_000_000;
        let expiration: i64 = 1_700_000_060_000;

        let raw = build_transfer_raw_data(
            &owner,
            &to,
            amount,
            &ref_block_bytes,
            &ref_block_hash,
            expiration,
            timestamp,
            None,
        );

        let expected_hex = "0a0200012208010203040506070840e0a499ffbc315a67080112630a2d747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e73666572436f6e747261637412320a15411111111111111111111111111111111111111111121541222222222222222222222222222222222222222218c0843d7080d095ffbc31";
        let expected = hex::decode(expected_hex).unwrap();

        assert_eq!(
            hex::encode(&raw),
            hex::encode(&expected),
            "TRON proto bytes diverge from tronweb reference"
        );

        // tx_id = SHA-256(raw_data)
        use sha2::{Digest, Sha256};
        let tx_id = Sha256::digest(&raw);
        assert_eq!(
            hex::encode(tx_id),
            "e0139655d946fbdeeff8a8a0bfe82453354b97245fab8c13fb3ba39016a494e2",
        );

        // Decoder round-trips: bytes → JSON → expected JSON shape.
        let decoded = decode_transfer_raw_to_json(&raw).unwrap();
        let expected_json = serde_json::json!({
            "contract": [{
                "parameter": {
                    "value": {
                        "owner_address": "411111111111111111111111111111111111111111",
                        "to_address": "412222222222222222222222222222222222222222",
                        "amount": 1_000_000,
                    },
                    "type_url": "type.googleapis.com/protocol.TransferContract",
                },
                "type": "TransferContract",
            }],
            "ref_block_bytes": "0001",
            "ref_block_hash": "0102030405060708",
            "expiration": 1_700_000_060_000i64,
            "timestamp": 1_700_000_000_000i64,
        });
        assert_eq!(decoded, expected_json);
    }

    /// Reference vector captured via `node scripts/tron-trc20-ref-vector.mjs`.
    /// Asserts byte-for-byte parity against `tronweb` for a TRC-20
    /// `transfer(address,uint256)` call wrapped in `TriggerSmartContract`.
    #[test]
    fn proto_matches_tronweb_trc20_reference() {
        let owner = hex::decode("411111111111111111111111111111111111111111").unwrap();
        let contract = hex::decode("419999999999999999999999999999999999999999").unwrap();
        let calldata = hex::decode(
            "a9059cbb000000000000000000000000222222222222222222222222222222222222222200000000000000000000000000000000000000000000000000000000000f4240"
        ).unwrap();
        let ref_block_bytes: [u8; 2] = [0x00, 0x01];
        let ref_block_hash: [u8; 8] = [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08];
        let timestamp: i64 = 1_700_000_000_000;
        let expiration: i64 = 1_700_000_060_000;
        let fee_limit: i64 = 100_000_000;

        let raw = build_trc20_transfer_raw_data(
            &owner,
            &contract,
            &calldata,
            &ref_block_bytes,
            &ref_block_hash,
            expiration,
            timestamp,
            fee_limit,
        );

        let expected_hex = "0a0200012208010203040506070840e0a499ffbc315aae01081f12a9010a31747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e54726967676572536d617274436f6e747261637412740a1541111111111111111111111111111111111111111112154199999999999999999999999999999999999999992244a9059cbb000000000000000000000000222222222222222222222222222222222222222200000000000000000000000000000000000000000000000000000000000f42407080d095ffbc31900180c2d72f";
        assert_eq!(
            hex::encode(&raw),
            expected_hex,
            "TRC-20 proto bytes diverge from tronweb reference"
        );

        // Decoder round-trips this through to the broadcast-shape JSON.
        let decoded = decode_transfer_raw_to_json(&raw).unwrap();
        let parameter = decoded["contract"][0]["parameter"]["value"].clone();
        assert_eq!(
            parameter["owner_address"],
            "411111111111111111111111111111111111111111"
        );
        assert_eq!(
            parameter["contract_address"],
            "419999999999999999999999999999999999999999"
        );
        assert_eq!(decoded["contract"][0]["type"], "TriggerSmartContract");
        assert_eq!(decoded["fee_limit"], serde_json::json!(fee_limit));
    }
}
