//! Hand-rolled minimal Protobuf encoder for TRON `Transaction.raw`.
//!
//! TRON's wire format is google Protobuf (proto3). We encode just enough of
//! the schema to ship a native TRX `TransferContract`. Keeping this in-tree
//! avoids pulling `prost` + `protoc` for one message family.
//!
//! Field map (verified against `protocol/Tron.proto` upstream):
//!
//! ```text
//! Transaction.raw {
//!     bytes ref_block_bytes = 1;
//!     bytes ref_block_hash  = 4;
//!     int64 expiration      = 8;
//!     repeated Contract contract = 11;
//!     int64 timestamp       = 14;
//!     int64 fee_limit       = 18;
//! }
//! Contract { ContractType type = 1; google.protobuf.Any parameter = 2; }
//! google.protobuf.Any { string type_url = 1; bytes value = 2; }
//! TransferContract {
//!     bytes owner_address = 1;  // 21 bytes (0x41 ‖ hash160)
//!     bytes to_address    = 2;
//!     int64 amount        = 3;  // sun
//! }
//! ```
//!
//! Reference vector pinned in tests is generated by `scripts/tron-ref-vector.mjs`
//! using `tronweb`'s native protobuf encoder, so we get byte-equality with the
//! validator-side decoder rather than guessing at field order or wire types.

const TRANSFER_TYPE_URL: &str = "type.googleapis.com/protocol.TransferContract";

// ── Wire-format primitives ──────────────────────────────────────────────────

fn write_varint(out: &mut Vec<u8>, mut v: u64) {
    while v >= 0x80 {
        out.push((v as u8) | 0x80);
        v >>= 7;
    }
    out.push(v as u8);
}

fn write_tag(out: &mut Vec<u8>, field_num: u32, wire_type: u32) {
    write_varint(out, ((field_num as u64) << 3) | (wire_type as u64));
}

fn write_bytes_field(out: &mut Vec<u8>, field_num: u32, data: &[u8]) {
    write_tag(out, field_num, 2);
    write_varint(out, data.len() as u64);
    out.extend_from_slice(data);
}

fn write_int64_field(out: &mut Vec<u8>, field_num: u32, v: i64) {
    write_tag(out, field_num, 0);
    // proto3 int64 is plain varint over the two's-complement representation.
    // Negative values would balloon to 10 bytes; for our positive timestamps
    // and amounts this is fine.
    write_varint(out, v as u64);
}

// ── TransferContract / Any / Contract / raw ─────────────────────────────────

pub fn encode_transfer_contract(owner: &[u8], to: &[u8], amount: i64) -> Vec<u8> {
    let mut out = Vec::with_capacity(2 + owner.len() + 2 + to.len() + 2 + 10);
    write_bytes_field(&mut out, 1, owner);
    write_bytes_field(&mut out, 2, to);
    write_int64_field(&mut out, 3, amount);
    out
}

pub fn encode_any_transfer(transfer: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(2 + TRANSFER_TYPE_URL.len() + 2 + transfer.len());
    write_bytes_field(&mut out, 1, TRANSFER_TYPE_URL.as_bytes());
    write_bytes_field(&mut out, 2, transfer);
    out
}

pub fn encode_contract_transfer(any: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(2 + 2 + any.len());
    // ContractType enum (TransferContract = 1)
    write_tag(&mut out, 1, 0);
    write_varint(&mut out, 1);
    write_bytes_field(&mut out, 2, any);
    out
}

#[allow(clippy::too_many_arguments)]
pub fn encode_raw_data(
    ref_block_bytes: &[u8; 2],
    ref_block_hash: &[u8; 8],
    expiration_ms: i64,
    contract_bytes: &[u8],
    timestamp_ms: i64,
    fee_limit_sun: i64,
) -> Vec<u8> {
    let mut out =
        Vec::with_capacity(2 + 2 + 2 + 8 + 2 + 8 + 2 + contract_bytes.len() + 2 + 8 + 2 + 8);
    write_bytes_field(&mut out, 1, ref_block_bytes);
    write_bytes_field(&mut out, 4, ref_block_hash);
    write_int64_field(&mut out, 8, expiration_ms);
    write_bytes_field(&mut out, 11, contract_bytes);
    write_int64_field(&mut out, 14, timestamp_ms);
    write_int64_field(&mut out, 18, fee_limit_sun);
    out
}

/// One-shot helper: build the full `Transaction.raw` bytes for a TransferContract.
#[allow(clippy::too_many_arguments)]
pub fn build_transfer_raw_data(
    owner_21: &[u8],
    to_21: &[u8],
    amount_sun: i64,
    ref_block_bytes: &[u8; 2],
    ref_block_hash: &[u8; 8],
    expiration_ms: i64,
    timestamp_ms: i64,
    fee_limit_sun: i64,
) -> Vec<u8> {
    let transfer = encode_transfer_contract(owner_21, to_21, amount_sun);
    let any = encode_any_transfer(&transfer);
    let contract = encode_contract_transfer(&any);
    encode_raw_data(
        ref_block_bytes,
        ref_block_hash,
        expiration_ms,
        &contract,
        timestamp_ms,
        fee_limit_sun,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn varint_roundtrip() {
        let cases = [0u64, 1, 127, 128, 255, 16_383, 16_384, 1_000_000, u64::MAX];
        for c in cases {
            let mut buf = Vec::new();
            write_varint(&mut buf, c);
            let (v, n) = read_varint(&buf).unwrap();
            assert_eq!(v, c, "value mismatch");
            assert_eq!(n, buf.len(), "consumed length mismatch");
        }
    }

    fn read_varint(buf: &[u8]) -> Option<(u64, usize)> {
        let mut v = 0u64;
        let mut shift = 0;
        for (i, &b) in buf.iter().enumerate() {
            v |= ((b & 0x7f) as u64) << shift;
            if b & 0x80 == 0 {
                return Some((v, i + 1));
            }
            shift += 7;
        }
        None
    }

    /// Reference vector captured via `node scripts/tron-ref-vector.mjs`.
    /// Asserts byte-for-byte parity against `tronweb`'s native protobuf encoder.
    #[test]
    fn proto_matches_tronweb_reference() {
        let owner = hex::decode("411111111111111111111111111111111111111111").unwrap();
        let to = hex::decode("412222222222222222222222222222222222222222").unwrap();
        let amount: i64 = 1_000_000;
        let ref_block_bytes: [u8; 2] = [0x00, 0x01];
        let ref_block_hash: [u8; 8] = [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08];
        let timestamp: i64 = 1_700_000_000_000;
        let expiration: i64 = 1_700_000_060_000;
        let fee_limit: i64 = 100_000_000;

        let raw = build_transfer_raw_data(
            &owner,
            &to,
            amount,
            &ref_block_bytes,
            &ref_block_hash,
            expiration,
            timestamp,
            fee_limit,
        );

        let expected_hex = "0a0200012208010203040506070840e0a499ffbc315a67080112630a2d747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e5472616e73666572436f6e747261637412320a15411111111111111111111111111111111111111111121541222222222222222222222222222222222222222218c0843d7080d095ffbc31900180c2d72f";
        let expected = hex::decode(expected_hex).unwrap();

        assert_eq!(
            hex::encode(&raw),
            hex::encode(&expected),
            "TRON proto bytes diverge from tronweb reference"
        );

        // tx_id = SHA-256(raw_data)
        use sha2::{Digest, Sha256};
        let tx_id = Sha256::digest(&raw);
        assert_eq!(
            hex::encode(tx_id),
            "27a4f25e6990634ff0172305f32c25b04e6ea79605238bfbfee30962ffbc2f1a",
        );
    }
}
